version: "3"
services:
  app:
    container_name: notCompla-back
    build: .
    env_file: ./.env
    volumes:
      - ../uploads:/app/uploads
    depends_on:
      - postgres
    ports:
      - "${EXPOSE_WEB_PORT:-8080}:3000"

  postgres:
    container_name: notCompla-pg
    image: postgres
    env_file: ./.env
    volumes:
      - ../db:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_DB_PORT:-5432}:5432"
